### ISSUE TITLE
Empty fasta output and biohansel.log but codes.log identified groups

### ISSUE THREAD

**Issue by jrober84** [almene/schemeDev#2]
[Data.zip](https://github.com/almene/schemeDev/files/4250824/Data.zip)
I have identified that there is the case where groups can be identified but the biohansel log and fasta file can be empty. I attached the data used to generate this.

I used the following:

srun -c1 python3 -m bioCanon --in_vcf __snippy/core.vcf --in_nwk __snippy/nj-snps-only.nwk  --reference __supplemental_material/NC_000913.fasta --min_snps 10 --min_members 1 --min_parent 0 --outdir bio_canno

**Comment by almene** [comment]
Fixed when the skipping over of alt snp state groups was repaired
