### ISSUE TITLE
Number of canonical SNPs identified for dataset too low

### ISSUE THREAD

**Issue by jrober84** [almene/schemeDev#3]
I have a dataset of 99 samples where 100% of the 530 variants correspond with branch points. I have uploaded the log files and source files for this run. 

python3 -m bioCanon --in_vcf __snippy/core.vcf --in_nwk __snippy/nj-snps-only.nwk  --reference __supplemental_material/NC_000913.fasta --min_snps 1 --min_members 1 --min_parent 1 --outdir bio_cannon

Only 26 of these variants were identified.

[codes.log](https://github.com/almene/schemeDev/files/4250656/codes.log)
[S1G1_biohansel.log](https://github.com/almene/schemeDev/files/4250657/S1G1_biohansel.log)

[Archive.zip](https://github.com/almene/schemeDev/files/4250927/Archive.zip)

**Comment by almene** [comment]
Fixed.  The error was in skipping over groups that all had the alternative snp state
