### ISSUE TITLE
SNP reporting update

### ISSUE THREAD

**Issue by jrober84** [almene/schemeDev#5]
A log file listing all of the SNPs considered and then a flag as to "ACCEPT" or "REJECT" and a reason would be a good enhancement so that people can see which SNPs are rejected and why. A summary at the end would be good as well:

SNPs in VCF: n
SNPs supporting branches: n
SNPs defining groups: n
Homoplasy SNPs: n
invariant SNPs: n
.
.
.

**Comment by almene** [comment]
Snp report has been included. Fixed in March 24th commits
