### ISSUE TITLE
User supplied group format needs to be more friendly to produce

### ISSUE THREAD

**Issue by jrober84** [almene/schemeDev#9]
The format for the tsv file should reflect a more straightforward way of representing groups. Generating files the current requested format is very cumbersome and repeats all of the information from the previous level

Something like this:
SampleID,Div1,Div2,Div3
A,1,1,1
B,1,2,1
C,2,1,1

OR

Sample,Code
A,1.1.1
B,1.2.1
C,2.1.1

**Comment by almene** [comment]
Altered to accept tsv file of sample \t code
